# Generated by Django 4.2.2 on 2023-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('usluga', 'Usługa'), ('material', 'Materiał')], max_length=10)),
                ('tax', models.IntegerField(choices=[(8, '8%'), (23, '23%')])),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
